[package]
name = "git-grid-cli"
version = "0.0.1"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]

[dependencies]
clap = "*"

[dependencies.git-grid]
# git = "file:/Users/cburgdorf/Documents/hacking/git-grid"
git = "https://github.com/thoughtram-editor/git-grid.git"
