[package]
name = "atelier-cli"
version = "0.0.1"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]

[dependencies]
clap = "*"

[dependencies.git-grid]
# git = "file:/Users/cburgdorf/Documents/hacking/atelier"
git = "https://github.com/thoughtram-editor/atelier.git"
